### ISSUE TITLE
Open source licence?

### ISSUE THREAD

**Issue by tjdett** [pwaller/https-redirect#1]
Could you please give this project an explicit open source licence?

I've created a [slim Docker image](https://hub.docker.com/r/dit4c/https-redirect/) for it, but it's in a legal grey area given the GitHub TOS (the default if no licence is specified) doesn't confer binary distribution rights.

**Comment by pwaller** [comment]
Thanks. I've also added a note to the README. Please submit a pull request if you want to tweak it.
